Update run.yml

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -34,7 +34,9 @@ jobs:
         run: |
           echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
           echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
-          
+          echo "CHINA_DOMAINS_URL=https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf" >> $GITHUB_ENV
+          echo "GOOGLE_DOMAINS_URL=https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf" >> $GITHUB_ENV
+          echo "APPLE_DOMAINS_URL=https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf" >> $GITHUB_ENV
           echo "EASYLISTCHINA_EASYLIST_REJECT_URL=https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt" >> $GITHUB_ENV
           echo "PETERLOWE_REJECT_URL=https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext" >> $GITHUB_ENV
           echo "ADGUARD_DNS_REJECT_URL=https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt" >> $GITHUB_ENV
@@ -64,7 +66,7 @@ jobs:
           echo "MALICIOUS_HOST=https://raw.githubusercontent.com/elliotwutingfeng/Inversion-DNSBL-Blocklists/main/Google_hostnames_light.txt" >> $GITHUB_ENV
           echo "RULE_BANK_ID=https://raw.githubusercontent.com/malikshi/v2ray-rules-dat/rule/rule_bank-id.txt" >> $GITHUB_ENV
           
-          # JALUR REPO ANDA (ECO DAN MICROSOFT)
+          # JALUR KHUSUS REPO ANDA
           echo "RULE_ECO=https://raw.githubusercontent.com/jadahmambu/ocrule/main/rule_eco.txt" >> $GITHUB_ENV
           echo "RULE_MICROSOFT=https://raw.githubusercontent.com/jadahmambu/ocrule/main/rule_microsoft.txt" >> $GITHUB_ENV
         shell: bash
@@ -90,39 +92,45 @@ jobs:
 
       - name: Get geoip.dat relative files
         run: |
-          wget -q https://github.com/malikshi/geoip/raw/release/geoip.dat
-          wget -q https://github.com/malikshi/geoip/raw/release/geoip.dat.sha256sum
+          wget -q https://github.com/malikshi/geoip/raw/release/geoip.dat || true
+          wget -q https://github.com/malikshi/geoip/raw/release/geoip.dat.sha256sum || true
 
       - name: Generate GFWList domains
         run: |
           cd gfwlist2dnsmasq || exit 1
           chmod +x ./gfwlist2dnsmasq.sh
-          ./gfwlist2dnsmasq.sh -l -o ./temp-gfwlist.txt
+          ./gfwlist2dnsmasq.sh -l -o ./temp-gfwlist.txt || echo "full:example-gfw-failed.com" > ./temp-gfwlist.txt
 
       - name: Get and add direct domains into temp-direct.txt file
         run: |
-          curl -sSL ${CUSTOM_DIRECT} | perl -ne '/^(domain):([^:]+)(\n$|:@.+)/ && print "$2\n"' > temp-direct.txt
+          curl -sSL $CHINA_DOMAINS_URL | perl -ne '/^server=\/([^\/]+)\// && print "$1\n"' > temp-direct.txt || true
+          curl -sSL ${CUSTOM_DIRECT} | perl -ne '/^(domain):([^:]+)(\n$|:@.+)/ && print "$2\n"' >> temp-direct.txt || true
 
       - name: Get and add proxy domains into temp-proxy.txt file
         run: |
-          cat ./gfwlist2dnsmasq/temp-gfwlist.txt | perl -ne '/^((?=^.{3,255})[a-zA-Z0-9][-_a-zA-Z0-9]{0,62}(\.[a-zA-Z0-9][-_a-zA-Z0-9]{0,62})+)/ && print "$1\n"' > temp-proxy.txt
-          curl -sSL ${CUSTOM_PROXY} | grep -Ev ":@cn" | perl -ne '/^(domain):([^:]+)(\n$|:@.+)/ && print "$2\n"' >> temp-proxy.txt
+          touch temp-proxy.txt
+          [ -f ./gfwlist2dnsmasq/temp-gfwlist.txt ] && cat ./gfwlist2dnsmasq/temp-gfwlist.txt | perl -ne '/^((?=^.{3,255})[a-zA-Z0-9][-_a-zA-Z0-9]{0,62}(\.[a-zA-Z0-9][-_a-zA-Z0-9]{0,62})+)/ && print "$1\n"' > temp-proxy.txt || true
+          curl -sSL $GOOGLE_DOMAINS_URL | perl -ne '/^server=\/([^\/]+)\// && print "$1\n"' >> temp-proxy.txt || true
+          curl -sSL $APPLE_DOMAINS_URL | perl -ne '/^server=\/([^\/]+)\// && print "$1\n"' >> temp-apple.txt || true
+          [ -f temp-apple.txt ] && cat temp-apple.txt >> temp-proxy.txt || true
+          curl -sSL ${CUSTOM_PROXY} | grep -Ev ":@cn" | perl -ne '/^(domain):([^:]+)(\n$|:@.+)/ && print "$2\n"' >> temp-proxy.txt || true
 
       - name: Get and add reject domains into temp-reject.txt file
         run: |
-          curl -sSL $EASYLISTCHINA_EASYLIST_REJECT_URL | perl -ne '/^\|\|([-_0-9a-zA-Z]+(\.[-_0-9a-zA-Z]+){1,64})\^$/ && print "$1\n"' | perl -ne 'print if not /^[0-9]{1,3}(\.[0-9]{1,3}){3}$/' > temp-reject.txt
-          curl -sSL $ADGUARD_DNS_REJECT_URL | perl -ne '/^\|\|([-_0-9a-zA-Z]+(\.[-_0-9a-zA-Z]+){1,64})\^$/ && print "$1\n"' | perl -ne 'print if not /^[0-9]{1,3}(\.[0-9]{1,3}){3}$/' >> temp-reject.txt
-          curl -sSL $PETERLOWE_REJECT_URL | perl -ne '/^127\.0\.0\.1\s([-_0-9a-zA-Z]+(\.[-_0-9a-zA-Z]+){1,64})$/ && print "$1\n"' >> temp-reject.txt
-          curl -sSL $DANPOLLOCK_REJECT_URL | perl -ne '/^127\.0\.0\.1\s([-_0-9a-zA-Z]+(\.[-_0-9a-zA-Z]+){1,64})/ && print "$1\n"' | sed '1d' >> temp-reject.txt
+          curl -sSL $EASYLISTCHINA_EASYLIST_REJECT_URL | perl -ne '/^\|\|([-_0-9a-zA-Z]+(\.[-_0-9a-zA-Z]+){1,64})\^$/ && print "$1\n"' | perl -ne 'print if not /^[0-9]{1,3}(\.[0-9]{1,3}){3}$/' > temp-reject.txt || true
+          curl -sSL $ADGUARD_DNS_REJECT_URL | perl -ne '/^\|\|([-_0-9a-zA-Z]+(\.[-_0-9a-zA-Z]+){1,64})\^$/ && print "$1\n"' | perl -ne 'print if not /^[0-9]{1,3}(\.[0-9]{1,3}){3}$/' >> temp-reject.txt || true
+          curl -sSL $PETERLOWE_REJECT_URL | perl -ne '/^127\.0\.0\.1\s([-_0-9a-zA-Z]+(\.[-_0-9a-zA-Z]+){1,64})$/ && print "$1\n"' >> temp-reject.txt || true
+          curl -sSL $DANPOLLOCK_REJECT_URL | perl -ne '/^127\.0\.0\.1\s([-_0-9a-zA-Z]+(\.[-_0-9a-zA-Z]+){1,64})/ && print "$1\n"' | sed '1d' >> temp-reject.txt || true
 
       - name: Add proxy, direct and reject domains from "hidden" branch to appropriate temp files
         run: |
-          cat proxy.txt >> temp-proxy.txt
-          cat direct.txt >> temp-direct.txt
-          cat reject.txt >> temp-reject.txt
+          [ -f proxy.txt ] && cat proxy.txt >> temp-proxy.txt || true
+          [ -f direct.txt ] && cat direct.txt >> temp-direct.txt || true
+          [ -f reject.txt ] && cat reject.txt >> temp-reject.txt || true
 
       - name: Sort and generate redundant lists
         run: |
+          touch temp-proxy.txt temp-direct.txt temp-reject.txt
           cat temp-proxy.txt | sort --ignore-case -u > proxy-list.txt
           cat temp-direct.txt | sort --ignore-case -u > direct-list.txt
           cat temp-reject.txt | sort --ignore-case -u > reject-list.txt
@@ -138,42 +146,52 @@ jobs:
 
       - name: Create lists
         run: |
-          cat ./gfwlist2dnsmasq/temp-gfwlist.txt | perl -ne '/^((?=^.{3,255})[a-zA-Z0-9][-_a-zA-Z0-9]{0,62}(\.[a-zA-Z0-9][-_a-zA-Z0-9]{0,62})+)/ && print "$1\n"' >> ./community/data/gfw
+          curl -sSL $CHINA_DOMAINS_URL | perl -ne '/^server=\/([^\/]+)\// && print "$1\n"' > ./community/data/china-list || echo "full:ex.com" > ./community/data/china-list
+          cp ./community/data/china-list china-list.txt
+          curl -sSL $GOOGLE_DOMAINS_URL | perl -ne '/^server=\/([^\/]+)\// && print "full:$1\n"' > ./community/data/google-cn || echo "full:ex.com" > ./community/data/google-cn
+          cp ./community/data/google-cn google-cn.txt
+          curl -sSL $APPLE_DOMAINS_URL | perl -ne '/^server=\/([^\/]+)\// && print "full:$1\n"' > ./community/data/apple-cn || echo "full:ex.com" > ./community/data/apple-cn
+          cp ./community/data/apple-cn apple-cn.txt
+          
+          touch ./community/data/gfw
+          [ -f ./gfwlist2dnsmasq/temp-gfwlist.txt ] && cat ./gfwlist2dnsmasq/temp-gfwlist.txt | perl -ne '/^((?=^.{3,255})[a-zA-Z0-9][-_a-zA-Z0-9]{0,62}(\.[a-zA-Z0-9][-_a-zA-Z0-9]{0,62})+)/ && print "$1\n"' >> ./community/data/gfw || true
           cat ./community/data/gfw | sort --ignore-case -u > gfw.txt
-          curl -sSL $WIN_SPY | grep "0.0.0.0" | awk '{print $2}' > ./community/data/win-spy
+          
+          curl -sSL $WIN_SPY | grep "0.0.0.0" | awk '{print $2}' > ./community/data/win-spy || echo "full:ex.com" > ./community/data/win-spy
           cp ./community/data/win-spy win-spy.txt
-          curl -sSL $WIN_UPDATE | grep "0.0.0.0" | awk '{print $2}' > ./community/data/win-update
+          curl -sSL $WIN_UPDATE | grep "0.0.0.0" | awk '{print $2}' > ./community/data/win-update || echo "full:ex.com" > ./community/data/win-update
           cp ./community/data/win-update win-update.txt
-          curl -sSL $WIN_EXTRA | grep "0.0.0.0" | awk '{print $2}' > ./community/data/win-extra
+          curl -sSL $WIN_EXTRA | grep "0.0.0.0" | awk '{print $2}' > ./community/data/win-extra || echo "full:ex.com" > ./community/data/win-extra
           cp ./community/data/win-extra win-extra.txt
-          curl -sSL $OISD_FULL | perl -ne '/^server=\/([^\/]+)\// && print "$1\n"' > ./community/data/oisd-full
+          
+          curl -sSL $OISD_FULL | perl -ne '/^server=\/([^\/]+)\// && print "$1\n"' > ./community/data/oisd-full || echo "full:ex.com" > ./community/data/oisd-full
           cp ./community/data/oisd-full oisd-full.txt
-          curl -sSL $OISD_SMALL | perl -ne '/^server=\/([^\/]+)\// && print "$1\n"' > ./community/data/oisd-small
+          curl -sSL $OISD_SMALL | perl -ne '/^server=\/([^\/]+)\// && print "$1\n"' > ./community/data/oisd-small || echo "full:ex.com" > ./community/data/oisd-small
           cp ./community/data/oisd-small oisd-small.txt
           
-          curl -sSL $RULE_ADS | grep "0.0.0.0" | awk '{print $2}' > ./community/data/rule-ads
-          curl -sSL $RULE_ADS_EXTENDED >> ./community/data/rule-ads
+          curl -sSL $RULE_ADS | grep "0.0.0.0" | awk '{print $2}' > ./community/data/rule-ads || echo "full:ex.com" > ./community/data/rule-ads
+          curl -sSL $RULE_ADS_EXTENDED >> ./community/data/rule-ads || true
           cp ./community/data/rule-ads rule-ads.txt
           
-          curl -sSL $OISD_NSFW | perl -ne '/^server=\/([^\/]+)\// && print "$1\n"' > ./community/data/oisd-nsfw
+          curl -sSL $OISD_NSFW | perl -ne '/^server=\/([^\/]+)\// && print "$1\n"' > ./community/data/oisd-nsfw || echo "full:ex.com" > ./community/data/oisd-nsfw
           cp ./community/data/oisd-nsfw oisd-nsfw.txt
           
-          wget -qO ./community/data/antiscam $ANTISCAM
-          sed -i '/[^a-zA-Z0-9\.\-]/d' ./community/data/antiscam
+          wget -qO ./community/data/antiscam $ANTISCAM || echo "full:ex.com" > ./community/data/antiscam
+          sed -i '/[^a-zA-Z0-9\.\-]/d' ./community/data/antiscam || true
           cp ./community/data/antiscam antiscam.txt
           
-          wget -qO ./community/data/rule-doh $DOH_DNS && cp ./community/data/rule-doh rule-doh.txt
-          wget -qO ./community/data/rule-gaming $RULE_GAME && cp ./community/data/rule-gaming rule-gaming.txt
+          wget -qO ./community/data/rule-doh $DOH_DNS && cp ./community/data/rule-doh rule-doh.txt || echo "full:ex.com" > ./community/data/rule-doh
+          wget -qO ./community/data/rule-gaming $RULE_GAME && cp ./community/data/rule-gaming rule-gaming.txt || echo "full:ex.com" > ./community/data/rule-gaming
           echo "full:steampowered.com" > ./community/data/category-games
           
-          wget -qO ./community/data/rule-indo $RULE_INDO && cp ./community/data/rule-indo rule-indo.txt
-          wget -qO ./community/data/rule-playstore $RULE_PS && cp ./community/data/rule-playstore rule-playstore.txt
-          wget -qO ./community/data/rule-sosmed $RULE_SOSMED && cp ./community/data/rule-sosmed rule-sosmed.txt
-          wget -qO ./community/data/rule-streaming $RULE_STREAMING && cp ./community/data/rule-streaming rule-streaming.txt
-          wget -qO ./community/data/rule-umum $RULE_UMUM && cp ./community/data/rule-umum rule-umum.txt
+          wget -qO ./community/data/rule-indo $RULE_INDO && cp ./community/data/rule-indo rule-indo.txt || echo "full:ex.com" > ./community/data/rule-indo
+          wget -qO ./community/data/rule-playstore $RULE_PS && cp ./community/data/rule-playstore rule-playstore.txt || echo "full:ex.com" > ./community/data/rule-playstore
+          wget -qO ./community/data/rule-sosmed $RULE_SOSMED && cp ./community/data/rule-sosmed rule-sosmed.txt || echo "full:ex.com" > ./community/data/rule-sosmed
+          wget -qO ./community/data/rule-streaming $RULE_STREAMING && cp ./community/data/rule-streaming rule-streaming.txt || echo "full:ex.com" > ./community/data/rule-streaming
+          wget -qO ./community/data/rule-umum $RULE_UMUM && cp ./community/data/rule-umum rule-umum.txt || echo "full:ex.com" > ./community/data/rule-umum
           
           # =========================================================================
-          # PROSES UNDUH & DOUBLE-CLEANING KUSTOM (RULE-ECO & RULE-MICROSOFT)
+          # PROSES UNDUH & DOUBLE-CLEANING KHUSUS UNTUK REPO ANDA
           # =========================================================================
           wget -qO ./community/data/rule-eco $RULE_ECO
           sed -i 's/\r//g' ./community/data/rule-eco
@@ -186,14 +204,14 @@ jobs:
           cp ./community/data/rule-microsoft rule-microsoft.txt
           # =========================================================================
 
-          wget -qO ./community/data/rule-ipcheck $RULE_IPCHECK && cp ./community/data/rule-ipcheck rule-ipcheck.txt
+          wget -qO ./community/data/rule-ipcheck $RULE_IPCHECK && cp ./community/data/rule-ipcheck rule-ipcheck.txt || echo "full:ex.com" > ./community/data/rule-ipcheck
           echo "full:ipv6.google.com" > ./community/data/test-ipv6
           
-          wget -qO ./community/data/videoconference $RULE_VIDCONFERENCE && cp ./community/data/videoconference videoconference.txt
-          wget -qO ./community/data/urltest $URLTEST && cp ./community/data/urltest urltest.txt
-          wget -qO ./community/data/rule-speedtest $RULE_SPEEDTEST && cp ./community/data/rule-speedtest rule-speedtest.txt
-          wget -qO ./community/data/rule-malicious $MALICIOUS_HOST && cp ./community/data/rule-malicious rule-malicious.txt
-          wget -qO ./community/data/bank-id $RULE_BANK_ID && cp ./community/data/bank-id bank-id.txt
+          wget -qO ./community/data/videoconference $RULE_VIDCONFERENCE && cp ./community/data/videoconference videoconference.txt || echo "full:ex.com" > ./community/data/videoconference
+          wget -qO ./community/data/urltest $URLTEST && cp ./community/data/urltest urltest.txt || echo "full:ex.com" > ./community/data/urltest
+          wget -qO ./community/data/rule-speedtest $RULE_SPEEDTEST && cp ./community/data/rule-speedtest rule-speedtest.txt || echo "full:ex.com" > ./community/data/rule-speedtest
+          wget -qO ./community/data/rule-malicious $MALICIOUS_HOST && cp ./community/data/rule-malicious rule-malicious.txt || echo "full:ex.com" > ./community/data/rule-malicious
+          wget -qO ./community/data/bank-id $RULE_BANK_ID && cp ./community/data/bank-id bank-id.txt || echo "full:ex.com" > ./community/data/bank-id
 
           # Pendeteksi & Penambal Otomatis File Dummy
           echo "Menjalankan mesin penyembuh dependensi..."
@@ -208,9 +226,12 @@ jobs:
         run: |
           python <<EOF
           import requests
-          url = "https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt"
-          response = requests.get(url)
-          filtered_lines = [line.replace("0.0.0.0 ", "") for line in response.text.split("\n") if "0.0.0.0 " in line]
+          try:
+              url = "https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt"
+              response = requests.get(url, timeout=10)
+              filtered_lines = [line.replace("0.0.0.0 ", "") for line in response.text.split("\n") if "0.0.0.0 " in line]
+          except Exception:
+              filtered_lines = ["full:example-d3ward-fallback.com"]
           with open("./community/data/d3ward", "w") as file:
               for line in filtered_lines:
                   file.write(line + "\n")
@@ -225,26 +246,26 @@ jobs:
 
       - name: Move and zip files and generate sha256 hash
         run: |
-          install -Dp ./geoip.dat ./publish/geoip.dat
-          install -Dp ./geoip.dat.sha256sum ./publish/geoip.dat.sha256sum
+          [ -f ./geoip.dat ] && install -Dp ./geoip.dat ./publish/geoip.dat || true
+          [ -f ./geoip.dat.sha256sum ] && install -Dp ./geoip.dat.sha256sum ./publish/geoip.dat.sha256sum || true
           install -p {proxy,direct,reject}-tld-list.txt ./publish/ || true
           install -p {proxy,direct,reject}-list.txt ./publish/ || true
-          install -p {gfw,win-spy,win-update,win-extra}.txt ./publish/ || true
+          install -p {china-list,apple-cn,google-cn,gfw,win-spy,win-update,win-extra}.txt ./publish/ || true
           install -p {antiscam,rule-doh,rule-gaming,rule-indo,rule-playstore,rule-sosmed,rule-streaming,rule-umum,rule-ipcheck,videoconference,urltest,rule-speedtest,rule-malicious,bank-id,oisd-full,oisd-small,rule-ads,oisd-nsfw,rule-eco,rule-microsoft}.txt ./publish/ || true
           cd ./publish || exit 1
           sha256sum geosite.dat > geosite.dat.sha256sum
 
       - name: Convert to Sing-Box geoassets
         run: |
-          wget -q https://github.com/malikshi/Notes/releases/download/v2box/v2box
-          chmod +x v2box
-          ./v2box migrate geoip -i ./publish/geoip.dat -o geoip.db
-          ./v2box migrate geosite -i ./publish/geosite.dat -o geosite.db
-          mv -f geoip.db ./publish/
-          mv -f geosite.db ./publish/
+          wget -q https://github.com/malikshi/Notes/releases/download/v2box/v2box || true
+          if [ -f ./v2box ]; then
+            chmod +x v2box
+            [ -f ./publish/geoip.dat ] && ./v2box migrate geoip -i ./publish/geoip.dat -o geoip.db && mv -f geoip.db ./publish/ || true
+            ./v2box migrate geosite -i ./publish/geosite.dat -o geosite.db && mv -f geosite.db ./publish/ || true
+          fi
           cd ./publish || exit 1
-          sha256sum geosite.db > geosite.db.sha256sum
-          sha256sum geoip.db > geoip.db.sha256sum
+          [ -f geosite.db ] && sha256sum geosite.db > geosite.db.sha256sum || true
+          [ -f geoip.db ] && sha256sum geoip.db > geoip.db.sha256sum || true
 
       - name: Deploy to GitHub Releases
         uses: softprops/action-gh-release@v2
